### ISSUE TITLE
Hi mate! Buttons on Main activity work through Guillotine

### ISSUE THREAD

**Issue by iRYO400** [Yalantis/GuillotineMenu-Android#11]
Thanks for cool menu. 
I think it's not an issue, but how can I disable buttons on Main, when open Guillotine menu?
Thanks again

**Comment by curliq** [comment]
nice pic

sry for off topic

**Comment by dmytroDenysenko** [comment]
Hi @iRYO400, you can use builder's method _setGuillotineListener()_  when building your animation. This listener has callback methods _onGuillotineOpened()_ and _onGuillotineClosed()_, where you can disable and enable your buttons.
