### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by mehdi-moslehi** [Yalantis/GuillotineMenu-Android#13]
hi , i have an issue loading this project on android studio 
when i load this project my android studio shows this error :
Failed to resolve: com.jakewharton:butterknife:6.1.0
is it because my sdk is not upgraded?
what can i do to fix this error ?

**Comment by dmytroDenysenko** [comment]
Hi @mehdi-moslehi 
Thanks for reporting this issue. It has nothing to do with your sdk. I updated dependencies in repo, you can use it now

**Comment by prasad456** [comment]
still i have issue 
ERROR: Failed to resolve: com.github.Yalantis:GuillotineMenu-Android:1.2
