### ISSUE TITLE
Using this with Unity3d?

### ISSUE THREAD

**Issue by RowanHarley** [Yalantis/GuillotineMenu-Android#16]
Is there any way I could get this to work on Unity3d? Look's great!

**Comment by dmytroDenysenko** [comment]
Hi @RowanHarley 
This lib isn't compatible with Unity3d as it is. But you can use code in GuillotineInterpolator.class to apply interpolation to animation in Unity3d.

**Comment by RowanHarley** [comment]
ok @cleanOK , Thanks!
