### ISSUE TITLE
Animation not smooth in RecycleView

### ISSUE THREAD

**Issue by burhanrashid52** [Yalantis/GuillotineMenu-Android#18]
I am inflating a layout for Guillotinemenu which contain a recycleview with gridlayout which contatin an image and text so when i click on menu button it open menu with not smooth animation...its stuck in between for few milliseconds and than open the menu..while in simple textview with drawble in your example work smoothly

**Comment by TeeRawk** [comment]
@burhanrashid52  I coldn't reproduce this issue. Maybe you can provide details ? Also check  whether or not your doing heavy work on the main thread, such as decoding bitmap maybe , or sending network request

**Comment by burhanrashid52** [comment]
@TeeRawk Same here...i am also not able to reproduce this issue again...I don't know what happened but now its working fine in my device and i was not sending any network request or any heavy bitmap decoding..i was loading very small size image from drawable so closing this issue
Thanks for your reply
