### ISSUE TITLE
Beautiful but not convenient.

### ISSUE THREAD

**Issue by HanderWei** [Yalantis/GuillotineMenu-Android#2]
I like it! It was beautiful. But I think it was not convenient cause I must click the menu icon.

I think it will be better that you rotate the drawer  90 degrees in clockwise direction and add sliding gesture like Navigating Drawer.

**Comment by dmytroDenysenko** [comment]
@HanderWei Completely agree with you on the swiping gesture. That's why I included it into the «features planned».
As for rotation in a clockwise direction, this falls out of the animation concept. The component just wasn’t designed this way.
However, we are always open for your pull requests.

**Comment by ppamorim** [comment]
You can use ViewDragHelper to provide this feature :)

**Comment by dmytroDenysenko** [comment]
@ppamorim Thanks! Will surely look into it.
