### ISSUE TITLE
Error inflating class CanaroTextView

### ISSUE THREAD

**Issue by mansoldm** [Yalantis/GuillotineMenu-Android#21]
I'm trying to implement this menu in my code and set everything up the same way as the example code provided, but when inflating the menu in the MainActivity onCreate() method, the app stops.
The following message is displayed 
                                                                                     `Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.CanaroTextView" on path: DexPathList[[zip file "/data/app/com.example.guillotinemenu.testapp-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]`

But I can't understand where the program is trying to get the android.view.CanaroTextView class, since throughout my program I'm always specifying the CanaroTextView class in my own package

**Comment by sagarrishabh** [comment]
hey how did you resolve this issue?
