### ISSUE TITLE
Right To Left Animation Problem!

### ISSUE THREAD

**Issue by aliarasteh** [Yalantis/GuillotineMenu-Android#24]
I want to have menu button on right side, the problem is animation starts from bottom to top and doesn't seem correct.
problem solved when I changed "GUILLOTINE_CLOSED_ANGLE" value from -90.0F to 90.0F.

**Comment by warko-san** [comment]
Hi, @aliarasteh! It's a known issue. Currently lib doen't support right-to-left layouts. Thank you for solution. If you want to help us to make it better - you can make pull request.
