### ISSUE TITLE
How do button work in menu

### ISSUE THREAD

**Issue by asad1492** [Yalantis/GuillotineMenu-Android#25]
I have just implemented "GuillotineMenu-Android" in my android project. In my menu xml files I have some button which perform some actions, for that actions I have to write click listeners for that buttons.The java file which I am attaching with that xml is not working. How can I make it operational?

**Comment by warko-san** [comment]
Hi, @asad1492! To make it work, you should be doing like this. 
To get needed view from Guillotine Menu you can call `guillotineMenu.findViewById(your_id_here)` and then `setOnClickListener()` on it.
