### ISSUE TITLE
Menu crashed on 4.2.2

### ISSUE THREAD

**Issue by ZaeemSattar** [Yalantis/GuillotineMenu-Android#26]
i used this menu in my application . this is so good and good looking in UI . But the problem occurs on 4.2.2 . when i tried to run app on 4.2.2 the menu crashed . if you have a solution to this problem kindly reply .

**Comment by warko-san** [comment]
Hi, @ZaeemSattar! Can you please attach the crash log?

**Comment by ZaeemSattar** [comment]
sure . i will send you tomorrow .i don't have screen shot now

**Comment by ZaeemSattar** [comment]
Thank you i just solve the issue . it was conflicting with toolbar .
