### ISSUE TITLE
How to programmatically check if the if the menu is opened or close??

### ISSUE THREAD

**Issue by DalveerSinghDaiya** [Yalantis/GuillotineMenu-Android#27]

**Comment by DalveerSinghDaiya** [comment]
:P found it.

**Comment by nikunjparadva** [comment]
How please tell me!!

**Comment by DalveerSinghDaiya** [comment]
Just implement the Interface viz. GuillotineListener in your activity, it will ask you to implement methods, doing so two methods will be overridden in your activity which will let you know if your menu is opened or not at runtime.

`public class Activity extends AppCompatActivity implements GuillotineListener{`

 
```
//    On Opening of the Guillotine Menu
 @Override
    public void onGuillotineOpened() {
        Log.d("Tag", "Opened");
    }

    //    On Closing of the Guillotine Menu
    @Override
    public void onGuillotineClosed() {
     Log.d("Tag", "Closing");
    }
}
```

**Comment by royabh1** [comment]
Hi! I have implemented the GuillotineListener as you have said, but that doesn't print any log. Please help me out. Thanks.
