### ISSUE TITLE
I still can click a button beneath guillotine menu

### ISSUE THREAD

**Issue by meeftah** [Yalantis/GuillotineMenu-Android#33]
so I used this guillotine menu library in my project, but I have an issue
I have a recyclerview and when I click it, it will go to another activity...
so when I open guillotine menu, I can click my recyclerview which is beneath guillotine menu on empty space in guillotine menu

is there any solution on this?

**Comment by meeftah** [comment]
I solved it....
I just adjust the layout to fill empty space

**Comment by udoy-touhid** [comment]
i have the same problem, please reply how you solve your problem @meeftah
