### ISSUE TITLE
open/close by code

### ISSUE THREAD

**Issue by masooddalman** [Yalantis/GuillotineMenu-Android#34]
hi
how to open/close menu by code?

**Comment by masooddalman** [comment]
12 days and no answer.
so i did it manually;
download project and add library to your project.

make GuillotineAnimation constructor PUBLIC.

in your activity:

make Builder like this:

> mBuilder = new GuillotineAnimation.GuillotineBuilder(guillotineMenu, guillotineMenu.findViewById(R.id.guillotine_hamburger), menu)
>                 .setStartDelay(RIPPLE_DURATION)
>                 .setActionBarViewForAnimation(toolbar)
>                 .setClosedOnStart(true); 

then make object from GuillotineAnimation class and pass the builder

> GuillotineAnimation ga=new GuillotineAnimation(mBuilder);

now you can open and close menu using code

> ga.open();
> ga.close();

**Comment by drummerjun** [comment]
HI,
I'm having the same question, thanks!

Or, is there an alternative to closing the menu upon selecting a Guillotine Menu Item?
Thanks

**Comment by BG-Kim** [comment]
Using GuillotineAnimation Open/Close Method.

Sample Code)
```
final Button btnClose = guillotineMenu.findViewById(R.id.btnCloseMenu);

final GuillotineAnimation aniMenu= new GuillotineAnimation.GuillotineBuilder(guillotineMenu, btnClose, btnMenu)
        .setStartDelay(100)
        .setActionBarViewForAnimation(toolbar.getRootView())
        .setClosedOnStart(true)
        .build();

btnClose.setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View view) {
        aniMenu.close();
    }
});
```

**Comment by kstanislav** [comment]
answer above is right
