### ISSUE TITLE
import butterknife.BindView; import butterknife.ButterKnife;

### ISSUE THREAD

**Issue by ZoyaEman** [Yalantis/GuillotineMenu-Android#36]
at start when we initialize have @BindView error. 
@BindView(R.id.toolbar)
    @BindView(R.id.root)
    FrameLayout root;
    @BindView(R.id.content_hamburger)

and in override method
ButterKnife.bind(this);

**Comment by smoralb** [comment]
When you make @BindView(R.id.toolbar) you must specify an object like you do with root. Your code should be 

@Bindview(R.id.toolbar)
Toolbar toolbar;
@Bindview(R.id.root)
FrameLayout root;
@Bindview(R.id.content_hamburger)
View hamburguer;
...

**Comment by kstanislav** [comment]
seems like @smoralb answer should solve this
