### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class

### ISSUE THREAD

**Issue by sebospc** [Yalantis/GuillotineMenu-Android#38]
Hi, when I download the example of guillotineMenu and I use it in android studio all works fine, but when I make copy/paste of that code (including dependiencies) this happens:
![image](https://user-images.githubusercontent.com/20503334/37789790-cafaf30c-2dd2-11e8-9fa4-71325cdea4ee.png)

and I try with code made by me but give me the same error. What I can do? :(

**Comment by udoy-touhid** [comment]
same happened to me

**Comment by kstanislav** [comment]
CanaroTextView is a class from sample. You can copy\paste it also (don't forget to change classpath in your main_activity .xml)
But GillotineMenu doesn't force you to use exactly CanaroTextView. Feel free to use regular TextView from Android SDK or AppCompatTextView from support library.
