### ISSUE TITLE
Problem with open angel

### ISSUE THREAD

**Issue by moali2402** [Yalantis/GuillotineMenu-Android#5]
There seems to be a problem with the Open angel of the menu.
I can see a bit from the main view from the right of the screen.
So its like over opened. 

Issue 2 : 

if i use setClosedOnStart() to true, the hamburger button animation doesn't work

**Comment by dmytroDenysenko** [comment]
@moali2402 Can you provide more info about this "angle" issue? What kind of device do you use, screenshot, some code?
As for "Issue 2", I will look into it ASAP.

**Comment by occamz** [comment]
The first issue is solved in https://github.com/Yalantis/GuillotineMenu-Android/issues/7.

I am interested in any pointers on how I could fix the setClosedOnStart() issue. Got any tips?

**Comment by fillbirdpa** [comment]
if i use 'setClosedOnStart(true) ', closingView and openingView have no animation effect。

**Comment by fillbirdpa** [comment]
@occamz  i found the problem, fix code in GuillotineAnimation.java like the following

if (builder.isClosedOnStart) {
            mGuillotineView.setRotation(GUILLOTINE_CLOSED_ANGLE);
            mGuillotineView.setVisibility(View.INVISIBLE);
        }

The problem is：if use GONE ，'closingView' can not get width & height  in  the method ‘setUpClosingView(final View closingView)’ .

**Comment by occamz** [comment]
@fillbirdpa Thank you. Figured it might've been something like that.

**Comment by dmytroDenysenko** [comment]
@fillbirdpa thanks for solution, will add it in an update
