### ISSUE TITLE
Issue in second bounce

### ISSUE THREAD

**Issue by tapanmodh** [Yalantis/GuillotineMenu-Android#7]
Hi,  Thanks for awesome library. I found one issue. After opening animation, little bit of behind layout is visible.You can see in sample example if you change background of root element in activity layout.

Please see attached image.red color is activity background color and slightly visible in right side.
![device-2015-07-09-000443](https://cloud.githubusercontent.com/assets/11678818/8578820/a5ef0486-25ce-11e5-95cc-893b2dfa0be5.png)

I found solution of that issue. You can verify from your side.

Change in GuillotineInterpolator class:

 private float secondBounce(float t) {
        return 0.625f \* t \* t - 1.083f \* t + 1.458f;
    }

**Comment by dmytroDenysenko** [comment]
@TapanM thanks for solution, will add it to an update
